#!/usr/bin/env python3
"""Scaffold a book-to-Obsidian-wiki processing workspace.

Creates ./build/[project_name] with a sources/, script/, and vaults/ folder,
copies this repo's scripts/skills/templates into it, and drops a README
explaining how to use the result.
"""
import argparse
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
SCRIPTS_SRC_DIR = REPO_ROOT / "scripts"
SKILLS_SRC_DIR = REPO_ROOT / "skills_src"
TEMPLATES_SRC_DIR = REPO_ROOT / "templates"
BUILD_ROOT = REPO_ROOT / "build"

PLATFORM_FOLDERS = {
    "agents": ".agents",
    "claude": ".claude",
    "opencode": ".opencode",
}

# source filename in templates/ -> destination filename under vaults/
TEMPLATE_RENAMES = {
    "article-style.template.md": ".article-style.md",
    "learning-goals.template.md": ".learning-goals.md",
}


def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="Build a book-processing workspace under ./build/[project_name].",
    )
    parser.add_argument(
        "project_name",
        help="Name of the workspace folder to create under ./build.",
    )
    parser.add_argument(
        "--platform",
        dest="agentic_platform",
        choices=sorted(PLATFORM_FOLDERS),
        default="agents",
        help="Target AI code assistant the skills are configured for. "
        "Default: agents (generic .agents folder).",
    )
    return parser.parse_args(argv)


def validate_project_name(project_name):
    if not project_name or project_name in (".", "..") or "/" in project_name or "\\" in project_name:
        sys.exit(f"error: invalid project_name {project_name!r} (must be a plain folder name)")


def copy_tree_contents(src_dir, dest_dir):
    dest_dir.mkdir(parents=True, exist_ok=True)
    for item in sorted(src_dir.iterdir()):
        dest = dest_dir / item.name
        if item.is_dir():
            shutil.copytree(item, dest, dirs_exist_ok=True)
        else:
            shutil.copy2(item, dest)


def build_workspace(project_name, agentic_platform):
    agent_platform_folder = PLATFORM_FOLDERS[agentic_platform]
    project_root = BUILD_ROOT / project_name

    for sub in ("sources", "scripts", "vaults"):
        (project_root / sub).mkdir(parents=True, exist_ok=True)

    platform_dir = project_root / agent_platform_folder
    platform_dir.mkdir(parents=True, exist_ok=True)

    # 1. copy this repo's scripts into the workspace's script/ folder
    copy_tree_contents(SCRIPTS_SRC_DIR, project_root / "scripts")

    # 2. copy every skill folder under skills_src/ into
    #    [agent_platform_folder]/skills/<skill-name>/ (Claude Code's own
    #    discovery convention: <name>/SKILL.md), a reasonable default for
    #    the other platforms too.
    copy_tree_contents(SKILLS_SRC_DIR, platform_dir / "skills")

    # 3. copy + rename the vault config templates
    vaults_dir = project_root / "vaults"
    for src_name, dest_name in TEMPLATE_RENAMES.items():
        shutil.copy2(TEMPLATES_SRC_DIR / src_name, vaults_dir / dest_name)

    write_readme(project_root, agentic_platform, agent_platform_folder)

    return project_root


def write_readme(project_root, agentic_platform, agent_platform_folder):
    readme = f"""# {project_root.name} — Book Processor Workspace

Generated by `build_workspace.py --platform {agentic_platform}`.

## Layout

```
sources/                 <- put source books here, one folder per book: sources/[book]/book.pdf
script/                  <- deterministic helper scripts (e.g. crosslink.py)
vaults/                  <- generated Obsidian output lands here, one folder per book
vaults/.article-style.md    <- workbench-wide article style defaults (edit freely)
vaults/.learning-goals.md   <- workbench-wide learning goals (edit freely)
{agent_platform_folder}/skills/         <- the AI skill pipeline for {agentic_platform}
```

## Adding a book

1. Create `sources/[book]/` and place the source file there as `book.pdf`.
2. From your AI code assistant, run the skills below against `[book]`.

## Skill pipeline

All skills are manual-invocation only — none of them fire automatically, always call them
explicitly in this order:

1. **`/book-guidelines [book]`** — reads `sources/[book]/book.pdf` and writes
   `vaults/[book]/book-guidelines.md`: a header, a two-level topic ontology, and
   chapter-by-chapter summaries. Run this first for every new book.
2. **`/book-topic-article [book] "[topic]"`** — writes one deep-dive article
   (`vaults/[book]/[Topic-Slug].md`) for a single topic, re-reading the source PDF
   directly for fidelity. Requires `book-guidelines.md` to already exist.
3. **`/book-topic-batch [book] [--deep] [--topics "..."] [--overwrite]`** — orchestrates
   `book-topic-article` across the whole Topic List in one pass (top-level topics only by
   default; pass `--deep` to also generate one article per subtopic). Skips articles that
   already exist unless `--overwrite` is given.
4. **`/book-crosslink [book] [--dry-run] [--verbose]`** — post-processing pass that wires
   the generated articles together: cross-links shared concepts between articles, links
   `book-guidelines.md`'s Topic List to the articles that now exist, and (re)builds
   `vaults/[book]/index.md`. Runs the bundled `script/crosslink.py`; safe and idempotent to
   re-run after every batch that adds new articles.

Optional per-book overrides: drop `vaults/[book]/.article-style.md` and/or
`vaults/[book]/.learning-goals.md` alongside the workbench-wide ones in `vaults/` — book-level
settings augment (never replace) the workbench defaults, and only win where they genuinely
conflict.

## Regenerating this workspace

From the repo root, re-run:

```bash
python3 build_workspace.py {project_root.name} --platform {agentic_platform}
```

This is safe to re-run: it recreates the folder structure and re-copies scripts/skills/templates,
but never touches `sources/` or already-generated `vaults/[book]/*.md` content.
"""
    (project_root / "README.md").write_text(readme, encoding="utf-8")


def main(argv=None):
    args = parse_args(argv)
    validate_project_name(args.project_name)

    for required in (SCRIPTS_SRC_DIR, SKILLS_SRC_DIR, TEMPLATES_SRC_DIR):
        if not required.is_dir():
            sys.exit(f"error: expected source folder missing: {required}")

    project_root = build_workspace(args.project_name, args.agentic_platform)
    print(f"Workspace built at {project_root}")
    print(f"Platform: {args.agentic_platform} ({PLATFORM_FOLDERS[args.agentic_platform]})")


if __name__ == "__main__":
    main()
